schema = 1
name = "x86_64-uefi"
architecture = "x86_64"
llvm_triple = "x86_64-unknown-windows"
object_format = "coff"
image_format = "pe-coff"
subsystem = "efi_application"
entry = "wrela_image_entry"
pointer_width = 64
endianness = "little"

[link]
driver = "lld-coff"
dynamic_linking = false
default_libraries = false
relocations = true

