schema = 2

[llvm]
version = "22.1.3"
tag = "llvmorg-22.1.3"
commit = "e9846648fd6183ee6d8cbdb4502213fcf902a211"
source = "https://github.com/llvm/llvm-project/releases/download/llvmorg-22.1.3/llvm-project-22.1.3.src.tar.xz"
sha256 = "2488c33a959eafba1c44f253e5bbe7ac958eb53fa626298a3a5f4b87373767cd"
bytes = 167045212
projects = ["lld"]
targets = ["AArch64"]
linkage = "static"

[inkwell]
version = "0.9.0"
llvm_feature = "llvm22-1-force-static"
target_features = ["target-aarch64"]
